[package]
name = "minihttp"
version = "0.1.0"
authors = ["Dennis Dietrich <d.dietrich84@gmail.com>"]

[dependencies]
futures = "0.1.1"
httparse = "1.1.2"
log = "0.3.6"
net2 = "0.2"
time = "0.1"
tokio-core = "0.1.0"
tokio-proto = "0.1"
service-fn = { git = "https://github.com/tokio-rs/service-fn" }
